name: Update Draft Release
"on":
    push:
        branches:
            - main
jobs:
    update:
        name: Update Draft Release
        runs-on:
            - ubuntu-latest
        steps:
            - id: release-drafter
              uses: release-drafter/release-drafter@v5
              env:
                GITHUB_TOKEN: ${{ secrets.JAVA_GITHUB_TOKEN }}
            - name: Install yj
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                echo "Installing yj ${YJ_VERSION}"

                mkdir -p "${HOME}"/bin
                echo "${HOME}/bin" >> "${GITHUB_PATH}"

                curl \
                  --location \
                  --show-error \
                  --silent \
                  --output "${HOME}"/bin/yj \
                  "https://github.com/sclevine/yj/releases/download/v${YJ_VERSION}/yj-linux"

                chmod +x "${HOME}"/bin/yj
              env:
                YJ_VERSION: 5.0.0
            - uses: actions/checkout@v3
            - name: Update draft release with buildpack information
              uses: paketo-buildpacks/actions/draft-release@latest
              with:
                github_token: ${{ secrets.JAVA_GITHUB_TOKEN }}
                release_body: ${{ steps.release-drafter.outputs.body }}
                release_id: ${{ steps.release-drafter.outputs.id }}
                release_name: ${{ steps.release-drafter.outputs.name }}
                release_tag_name: ${{ steps.release-drafter.outputs.tag_name }}
